default_to_none = true
id = "cAturmAsya-vrata-pAraNa-niSiddha-yOgaH"
tags = [ "CommonFestivals",]
jsonClass = "HinduCalendarEvent"
shlokas = """
रेवतीतुर्यचरणे द्वादशीसंयुते नरः।
न कुर्यात् पारणं कुर्वन्व्रतं निष्फलतां नयेत्॥३०॥
---श्रीस्कान्दे महापुराणे द्वितीये वैष्णवखण्डे कार्तिकमासमाहात्म्ये कूष्माण्डनवमीतुलसीविवाहविधिवर्णनं नामैकत्रिंशोऽध्यायः
"""
references_primary = [ "Skanda Puranam",]

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 8
window = "sunrise_to_sunset"
jsonClass = "HinduCalendarEventTiming"

[[timing.intersection_groups]]
[[timing.intersection_groups.angas]]
anga_type = "nakshatra_pada"
anga_number = 108
[[timing.intersection_groups.angas]]
anga_type = "tithi"
anga_number = 12

[description]
en = "When the last `pAda` of the Revati asterism is conjoined with Dvadashi tithi, it is not appropriate to break the fast---renders the vratam futile."

[names]
sa = [ "चातुर्मास्य-व्रत-पारण-निषिद्ध-योगः",]
