default_to_none = true
id = "gOvinda-dAmOdara-svAmigal-ArAdhana"
tags = [ "MahapurushaEvents", "CommonFestivals",]
references_secondary = [ "https://mahaperiyavaa.blog/2016/02/06/sri-angaraitriplicane-periyava-aradhana/",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "vyaapti"
month_number = 10
anga_type = "tithi"
anga_number = 28
kaala = "अपराह्णः"
year_start = 5105
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Aradhana Day of Govinda Damodara Swamigal. Sri Angarai Periyava (1992 sanyasa name “Ramachandrashraya”, also called Govinda Damodara Swamigal and Triplicane/Tiruvallikeni Periyava) was born Sri Kalyanarama Sastrigal (Bhagavathar) of Angarai village near Tiruchi. On the advice of the Kanchi Paramacharya (Mahaperiyava), he gave up his Indian Postal Department job despite having a large family to support, and devoted himself to the “Bhagavatha jeevanam” — performing seven-day Saptaha Parayanam recitals of the Srimad Bhagavatam and Bhattadri's Narayaneeyam with evening Tamil discourses, which he did before Janmashtami every year from 1973 to 1991 in the Paramacharya's presence. Renowned for extreme humility, simplicity and devotion to Rama and Guruvayurappan, he shunned all publicity, refused large audiences, and lived quietly for most of his life on Hanumantharayan Koil Street in Triplicane near the Parthasarathi temple. Mahaperiyava's own purvashrama younger brother “Sivan Sir” sent devotees to him for counsel. His adhishtanam is at Pazhur (https://maps.app.goo.gl/Jqu5xvrJXhV1HP3p9). He attained siddhi in 2004. Shri Ganapathy has written a beautiful article about Swamigal, on how He led His life as mentioned in Ramayanam (http://valmikiramayanam.in/wordpress/svkr.pdf)."

[names]
sa = [ "गोविन्द-दामोदर-स्वामिनः आराधना",]
