default_to_none = true
id = "prabOdhOtsavaH"
tags = [ "CommonFestivals",]
jsonClass = "HinduCalendarEvent"
shlokas = """
अथ कार्तिकशुक्लैकादश्यां प्रबोधविधिः॥
हेमाद्रौ ब्राह्मे—
एकादश्यां तु शुक्लायां कार्तिके मासे केशवम्।
प्रसुप्तं बोधयेद्रात्रौ श्रद्धाभक्तिसमन्वितः॥
नृत्यैर्गीतैस्तथा वेदैरृग्यजुःसाममङ्गलैः।
वीणापणवशब्दैश्च पुराणश्रवणेन च॥
वासुदेवकथाभिश्च स्तोत्रैरन्यैश्च वैष्णवैः।
सुभाषितैरिन्द्रजालैर्भूरिशोभाभिरेव च॥
पुष्पैर्धूपैश्च नैवेद्यैर्दीपवृक्षैः सुशोभनैः।
होमैर्भक्ष्यैरपूपैश्च फलैः शर्करपायसैः॥
इक्षोर्विकारैर्मधुरैर्द्राक्षाक्षौद्रैः सदाडिमैः।
कुठेरकस्य मञ्जर्या मालत्या कमलेन च॥
(कुठेरकः—पर्णाशः, कृष्णतुलसीति केचित्॥)
हृताभ्यां श्वेतरक्ताभ्यां चन्दनाभ्यां च सर्वदा।
कुङ्कुमालक्तकाभ्यां च रक्तसूत्रैः सकङ्कणैः॥
तथा नानाविधैः पुष्पैर्द्रव्यैर्वीरक्रयाहृतैः॥
(विक्रेत्रा प्रथमतोऽभिहितं मूल्यं दत्त्वा क्रियमाणः क्रयो वीरक्रयः॥)
तस्यां रात्र्यां व्यतीतायां द्वादश्यामरुणोदये।
आदौ घृतेनैक्षवेण मधुना स्नापयेत्ततः॥
दध्ना क्षीरेण च तथा पञ्चगव्येन शास्त्रवित्।
उद्वर्तनं माषचूर्णं मधुरामलकानि च॥
सर्षपाश्च प्रियंगुश्च मातुलिंगरसस्तथा।
सर्वौषध्यः सर्वगन्धाः सर्वबीजानि काञ्चनम्॥
मङ्गलानि यथाकामं रत्नानि च कुशोदकम्।
एवं संशोध्य देवेशं दद्याद्गोरोचनं शुभम्॥
ततस्तु कलशान् स्थाप्य यथाप्राप्तांस्त्वलंकृतान्।
जातीपल्लवसंयुक्तान्सफलांश्च सकाञ्चनान्॥
पुण्याहवेदशब्देन वीणावेणुरवेण च।
एवं संस्नाप्य गोविन्दं स्वनुलिप्तं स्वलंकृतम्॥
सुवाससं तु संपूज्य सुमनोभिः सकुंकुमैः।
धूपैर्दीपैर्मनोज्ञैश्च पायसेन च भूरिणा॥
हविष्यैश्चान्नदानैश्च होमैः पुष्पैः सदक्षिणैः।
वासोभिर्भूषणैरन्यैर्गोभिरश्वैर्मनोजवैः॥
ब्राह्मणाः पूजनीयाश्च विष्णोरीड्याश्च मूर्तयः।
यत्तु शिष्टामृतं पश्चाद्भोक्तव्यं ब्राह्मणैः सह॥
इति प्रबोधोत्सवविधिः॥
---व्रतराजे
"""
references_primary = [ "Vrataraja",]

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 8
anga_type = "tithi"
anga_number = 12
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "प्रबोधोत्सवः",]
