default_to_none = true
id = "mahAzivarAtriH"
tags = [ "CommonFestivals",]
jsonClass = "HinduCalendarEvent"
shlokas = """
श्रीब्रह्मवैवर्ते महापुराणे ब्रह्मखण्डे सौतिशौनकसंवादे नारदं प्रति शिवोपदेशे भक्ष्याभक्ष्यादिविवरणं नाम सप्तविंशतितमोऽध्यायः---
जन्माष्टमीदिने रामनवमीदिवसे हरेः।
शिवरात्रौ च यो भुङ्क्ते सोऽपि द्विगुणपातकी॥११॥
महेश्वर उवाच---
शृणु देवि व्रतं गुह्यं व्रतानामुत्तमोत्तमम्।
यत्र कस्यचिदाख्यातं रहस्यं मुक्तिदायकम्॥२६॥
येन वै कथ्यमानेनाप्यधर्मो विलयं व्रजेत्।
तदहं कीर्तयिष्यामि शृणुष्वैकाग्रमानसा॥२७॥
माघफाल्गुनयोर्मध्ये कृष्णपक्षे चतुर्दशी।
शिवरात्रिरिति ख्याता सर्वयज्ञोत्तमोत्तमा॥२८॥
दानयज्ञतपस्तीर्थव्रतकर्माणि यानि च।
शिवरात्रिव्रतस्यापि कोट्यंशेन समानि न॥२९॥
यैरियं कलिहन्त्री च कृतान्तपथनाशिनी।
भुक्तिदा मुक्तिदा देवि दिवानिशमुपोषिता।
न ते यमपुरं यान्ति सत्यं सत्यं वरानने॥३०॥
---श्रीपाद्मे महापुराण उत्तरखण्डे माघमाहात्म्ये वसिष्ठदिलीपसंवादे शिवरात्रि-प्रभावकथनं नाम चत्वारिंशदधिकद्विशततमोऽध्यायः॥२४०॥
[वीरमित्रोदये समयप्रकाशे] तथाऽन्यत्र---
कश्चित्पूण्यविशेषेण जलहीनोऽपि यः पुमान्।
जागरं कुरुते तत्र स रुद्रसमतां व्रजेत्॥
"""

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "paraviddha"
month_number = 11
anga_type = "tithi"
anga_number = 29
kaala = "निशीथः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "All related events e.g. kAmadahanam"

[names]
sa = [ "महाशिवरात्रिः",]
