default_to_none = true
id = "anadhyAyaH~zakradhvajotthApanam"
tags = [ "Anadhyayana Days",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
anchor_festival_id = "zakradhvajotthApanam"
offset = 0
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "अनध्यायः",]
