default_to_none = true
id = "bhOgi"
tags = [ "CommonFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
anchor_festival_id = "makara-saGkramaNa-puNyakAlaH"
offset = -1
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Bhogi, the first day of the Tamil Poṅkal festival, observed on the day before Makara Saṅkramaṇa; old and unwanted belongings are discarded and burnt in bonfires."

[names]
ta = [ "bhOgi",]
