default_to_none = true
id = "grahaNa-sAmAnya-niyamAH"
tags = [ "RareDays", "Eclipses",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "General notes: Avoid touching anything other than what's needed for the anushthana (especially bed/mat/cloth) until the mokSha snAna after the eclipse ends -- this is grahaNa Ashaucham. Do not sleep or attend to natural impulses during the eclipse. Mantra japa and dAna during the puNya kAla are of immense benefit. Do not view the eclipse with naked eyes. Pregnant women should avoid exposure to the sun/moon's light during the respective eclipse."

[names]
sa = [ "ग्रहणसामान्यनियमाः",]
