default_to_none = true
id = "kan2up~poGgal"
tags = [ "CommonFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
anchor_festival_id = "makara-saGkramaNa-puNyakAlaH"
offset = 1
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Kanu Pongal is observed on the morning after Thai Pongal, the day of Makara Saṅkramaṇa. At dawn, women and girls lay turmeric leaves in the open courtyard and set out offerings of pongal, coloured rice balls, sugarcane, etc. for crows and other birds, praying, as they do so, for the well-being and prosperity of their brothers."

[names]
ta = [ "kan2up~poGgal",]
