default_to_none = true
id = "hOlikA-pUrNimA"
tags = [ "SpecialPuja", "CommonFestivals",]
jsonClass = "HinduCalendarEvent"
shlokas = """
फाल्गुने पूर्णिमायां तु होलिकापूजनं मतम्॥१२४-७६॥
सञ्चयं सर्वकाष्ठानामुपलानां च कारयेत्।
तत्राग्निं विधिवद्ध्रुत्वा रक्षोघ्नैर्मन्त्रविस्तरैः॥१२४-७७॥
असृक्पाभयसन्त्रस्तैः कृता त्वं होलि बालिशैः।
अतस्त्वां पूजयिष्यामि भूते भूतिप्रदा भव॥१२४-७८॥
इति मन्त्रेण सन्दीप्य काष्ठादिक्षेपणैस्ततः।
परिक्रम्योत्सवः कार्य्यो गीतवादित्रनिःस्वनैः॥१२४-७९॥
होलिका राक्षसी चेयं प्रह्लादभयदायिनी।
ततस्तां प्रदहन्त्येवं काष्ठाद्यैर्गीतमङ्गलैः॥१२४-८०॥
"""
references_primary = [ "Naradiya Puranam, Adhyaya 124",]


[timing]
default_to_none = true
month_type = "lunar_month"
priority = "paraviddha"
month_number = 12
anga_type = "tithi"
anga_number = 15
kaala = "प्रदोषः"
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "होलिका-पूर्णिमा",]
