default_to_none = true
id = "anadhyAyaH-ayana-viSu-sAmAnya-niyamAH"
tags = [ "Anadhyayana Days",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "On the days of Ayana (solstices), Vishu (equinoxes), the day when Bhagavan Vishnu goes to sleep (Shayana Ekadashi) or awakens (Utthana Ekadashi) as well as the Manvadi and Yugadi days, one is not supposed to perform Adhyayana."

[names]
sa = [ "अनध्यायः",]
