default_to_none = true
id = "anadhyAyaH~yajur-utsarga~3"
tags = [ "Anadhyayana Days",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
anchor_festival_id = "taittirIya-utsargaH_paurNamAsyAm"
offset = 2
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "अनध्यायः",]
